# Print results to screen
cat('*** Continuity Equations Test! ***\n\n')
cat('Data file used: ', data.file, '\n\n')
cat('Modeling was performed using the lm, systemfit and vars packages and resulted in the following\nmodels:\n')
cat('\n')
cat('* LRM *\n')
cat('Model: IS ~ SO + GS\n')
cat('R-squared (adjusted): ', summary(model.lrm)$adj.r.squared, '\n')
cat('\n')
cat('* SEM *\n')
cat('Model: IS ~ GS\n')
cat('\n')
cat('* VAR *\n')
cat('Model: y ~ ', toString(formula(model.var$varresult$IS)[3]), '\n')
cat('R-squared (adjusted): ', summary(model.var$varresult$IS)$adj.r.squared, '\n')
cat('\n')
cat('* RVAR *\n')
cat('Model: y ~ ', toString(formula(model.var.restricted$varresult$IS)[3]), '\n')
cat('R-squared (adjusted): ', summary(model.var.restricted$varresult$IS)$adj.r.squared, '\n')
cat('\n')

cat('Test was run ', repetitions, 'times, with ', injection.size, ' anomalies injected each repetition.\n\n')

cat('Average of Type I (false positive) errors:\n')
cat('LRM:        ', mean(model.lrm.T1.error.count), ' ( min: ', min(model.lrm.T1.error.count),' max: ', max(model.lrm.T1.error.count), ' stdev: ', sd(model.lrm.T1.error.count), ' pre-test: ', model.lrm.pre.error.count,')\n')
cat('SEM:        ', mean(model.sem.T1.error.count), ' ( min: ', min(model.sem.T1.error.count),' max: ', max(model.sem.T1.error.count), ' stdev: ', sd(model.sem.T1.error.count), ' pre-test: ', model.sem.pre.error.count,')\n')
cat('VAR:        ', mean(model.var.T1.error.count), ' ( min: ', min(model.var.T1.error.count),' max: ', max(model.var.T1.error.count), ' stdev: ', sd(model.var.T1.error.count), ' pre-test: ', model.var.pre.error.count,')\n')
cat('RVAR:       ', mean(model.rvar.T1.error.count), ' ( min: ', min(model.rvar.T1.error.count),' max: ', max(model.rvar.T1.error.count), ' stdev: ', sd(model.rvar.T1.error.count), ' pre-test: ', model.rvar.pre.error.count,')\n')
cat('RVAR->VAR:  ', mean(model.combi.T1.error.count), ' ( min: ', min(model.combi.T1.error.count),' max: ', max(model.combi.T1.error.count), ' stdev: ', sd(model.combi.T1.error.count), ' pre-test: ', model.combi.pre.error.count,')\n')
cat('ARIMA(IS):  ', mean(model.arima.T1.error.count), ' ( min: ', min(model.arima.T1.error.count),' max: ', max(model.arima.T1.error.count), ' stdev: ', sd(model.arima.T1.error.count), ' pre-test: ', model.arima.pre.error.count,')\n')
cat('ETS(IS):    ', mean(model.ets.T1.error.count), ' ( min: ', min(model.ets.T1.error.count),' max: ', max(model.ets.T1.error.count), ' stdev: ', sd(model.ets.T1.error.count), ' pre-test: ', model.ets.pre.error.count,')\n')
cat('\n')

cat('Average of Type II (false negative) errors:\n')
cat('LRM:        ', mean(model.lrm.T2.error.count), ' ( min: ', min(model.lrm.T2.error.count),' max: ', max(model.lrm.T2.error.count), ' stdev: ', sd(model.lrm.T2.error.count), ' injected: ', injection.size,')\n')
cat('SEM:        ', mean(model.sem.T2.error.count), ' ( min: ', min(model.sem.T2.error.count),' max: ', max(model.sem.T2.error.count), ' stdev: ', sd(model.sem.T2.error.count), ' injected: ', injection.size,')\n')
cat('VAR:        ', mean(model.var.T2.error.count), ' ( min: ', min(model.var.T2.error.count),' max: ', max(model.var.T2.error.count), ' stdev: ', sd(model.var.T2.error.count), ' injected: ', injection.size,')\n')
cat('RVAR:       ', mean(model.rvar.T2.error.count), ' ( min: ', min(model.rvar.T2.error.count),' max: ', max(model.rvar.T2.error.count), ' stdev: ', sd(model.rvar.T2.error.count), ' injected: ', injection.size,')\n')
cat('RVAR->VAR:  ', mean(model.combi.T2.error.count), ' ( min: ', min(model.combi.T2.error.count),' max: ', max(model.combi.T2.error.count), ' stdev: ', sd(model.combi.T2.error.count), ' injected: ', injection.size,')\n')
cat('ARIMA(IS):  ', mean(model.arima.T2.error.count), ' ( min: ', min(model.arima.T2.error.count),' max: ', max(model.arima.T2.error.count), ' stdev: ', sd(model.arima.T2.error.count), ' injected: ', injection.size,')\n')
cat('ETS(IS):    ', mean(model.ets.T2.error.count), ' ( min: ', min(model.ets.T2.error.count),' max: ', max(model.ets.T2.error.count), ' stdev: ', sd(model.ets.T2.error.count), ' injected: ', injection.size,')\n')
